version: '3.1'
services:
  some-db:
    container_name: some-db
    image: mongo
    ports:
      - 9000:27017
    volumes:
      - craigslist-vehicles:/data/db
  mongo-express:
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: 'root'
      ME_CONFIG_BASICAUTH_PASSWORD: 'llWgNBRiaX7rwBsN4z'
    image: mongo-express
    ports:
      - 8080:8081
    restart: always
volumes:
  craigslist-vehicles: