version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27777:27017
    volumes:
      - ./volume:/data/db
  mongo-express:
    image: mongo-express
    ports:
      - 27778:8081
    restart: always
