version: '3.1'
services:
  mongo-cv:
    command: "mongod --auth"
    container_name: mongo-cv
    image: mongo
    ports:
      - 9000:27017
    volumes:
      - craigslist-vehicles:/data/db
  mongo-express:
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: 'root'
      ME_CONFIG_BASICAUTH_PASSWORD: 'llWgNBRiaX7rwBsN4z'
      ME_CONFIG_MONGODB_ADMINUSERNAME: 'root'
      ME_CONFIG_MONGODB_ADMINPASSWORD: 'FDKK8IyFwcET12DDkI1'
      ME_CONFIG_MONGODB_SERVER: mongo-cv
    image: mongo-express
    ports:
      - 8080:8081
    restart: always
volumes:
  craigslist-vehicles: